# Generated by Django 6.0.4 on 2026-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('learner_name', models.TextField(blank=True, null=True)),
                ('learner_email', models.TextField(blank=True, null=True)),
                ('learner_phone', models.TextField(blank=True, null=True)),
                ('learner_address', models.TextField(blank=True, null=True)),
                ('programme', models.TextField(blank=True, null=True)),
                ('manager_name', models.TextField(blank=True, null=True)),
                ('manager_email', models.TextField(blank=True, null=True)),
                ('coach_name', models.TextField(blank=True, null=True)),
                ('coach_email', models.TextField(blank=True, null=True)),
                ('coach_phone', models.TextField(blank=True, db_column='Coach_Phone', null=True)),
                ('organization_name', models.TextField(blank=True, db_column='OrganizationName', null=True)),
                ('submission_json', models.JSONField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('category_1_score', models.FloatField(blank=True, db_column='personal_wellbeing_protective_factors_score', null=True)),
                ('category_2_score', models.FloatField(blank=True, db_column='emotional_stress_resilience_score', null=True)),
                ('category_3_score', models.FloatField(blank=True, db_column='provider_culture_support_score', null=True)),
                ('category_4_score', models.FloatField(blank=True, db_column='safeguarding_vulnerability_score', null=True)),
                ('trigger_count', models.IntegerField(blank=True, default=0, null=True)),
                ('risk_level', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('history_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wellbeing_safeguarding_monitoring_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafeguardingQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_no', models.SmallIntegerField()),
                ('category_name', models.TextField()),
                ('question_order', models.IntegerField()),
                ('construct_type', models.TextField()),
                ('question_text', models.TextField()),
                ('scale_prompt', models.TextField(blank=True, null=True)),
                ('min_score', models.SmallIntegerField()),
                ('max_score', models.SmallIntegerField()),
                ('is_trigger', models.BooleanField()),
                ('trigger_rule', models.TextField(blank=True, null=True)),
                ('is_reverse_scored', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('score_group', models.TextField(blank=True, null=True)),
                ('question_code', models.TextField(blank=True, null=True)),
                ('is_core', models.BooleanField(default=True)),
                ('rotation_cycle', models.IntegerField(blank=True, null=True)),
                ('trigger_key', models.TextField(blank=True, null=True)),
                ('trigger_priority', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safeguarding_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafeguardingWellbeingAutomation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wellbeing_record_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('apprentice_dashboard', models.TextField(blank=True, null=True)),
                ('follow_up_by_coach', models.TextField(blank=True, db_column='Follow-up_by_Coach', null=True)),
                ('suggested_coach_actions', models.TextField(blank=True, db_column='Suggested_Coach_Actions', null=True)),
            ],
            options={
                'db_table': 'safeguarding_wellbeing_automation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wellbeing_record_id', models.BigIntegerField(blank=True, null=True)),
                ('ticket_type', models.TextField()),
                ('full_name', models.TextField()),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('details', models.TextField()),
                ('urgency', models.TextField(blank=True, null=True)),
                ('preferred_contact', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
