from django.urls import path
from .views import (
    login_view,
    admin_login_view,
    admin_microsoft_start_view,
    admin_microsoft_callback_view,
    admin_register_view,
    admin_change_password_view,
    admin_forgot_password_view,
    admin_reset_password_view,
    admin_me_view,
    admin_learners_view,
    admin_learner_token_view,
    instructions_view,
    quiz_status_view,
    start_quiz_view,
    questions_view,
    submit_quiz_view,
    result_view,
    send_result_to_employer_view,
    notify_employer_view,
    automation_dashboard_view,
    create_ticket_view,
    onboarding_progress_view,
    onboarding_reports_view,
    onboarding_sections_view,
    onboarding_questions_view,
    onboarding_submit_view,
)

urlpatterns = [
    path("auth/login/", login_view),
    path("admin/auth/login/", admin_login_view),
    path("admin/auth/microsoft/start/", admin_microsoft_start_view),
    path("admin/auth/microsoft/callback/", admin_microsoft_callback_view),
    path("admin/auth/register/", admin_register_view),
    path("admin/auth/change-password/", admin_change_password_view),
    path("admin/auth/forgot-password/", admin_forgot_password_view),
    path("admin/auth/reset-password/", admin_reset_password_view),
    path("admin/me/", admin_me_view),
    path("admin/learners/", admin_learners_view),
    path("admin/learners/<int:learner_id>/token/", admin_learner_token_view),
    path("quiz/instructions/", instructions_view),
    path("quiz/status/", quiz_status_view),
    path("quiz/start/", start_quiz_view),
    path("quiz/questions/", questions_view),
    path("quiz/submit/", submit_quiz_view),
    path("quiz/results/<int:attempt_id>/", result_view),
    path("quiz/results/<int:attempt_id>/send-to-employer/", send_result_to_employer_view),
    path("quiz/results/<int:attempt_id>/notify-employer/", notify_employer_view),
    path("quiz/results/<int:attempt_id>/automation-dashboard/", automation_dashboard_view),
    path("tickets/create/", create_ticket_view),
    path("onboarding/progress/", onboarding_progress_view),
    path("onboarding/reports/", onboarding_reports_view),
    path("onboarding/sections/", onboarding_sections_view),
    path("onboarding/sections/<str:section_id>/questions/", onboarding_questions_view),
    path("onboarding/sections/<str:section_id>/submit/", onboarding_submit_view),
]
